### ISSUE TITLE
php8 Kompatibilität

### ISSUE THREAD

**Issue by geimist** [geimist/GuestCal#1]
Mit der Umstellung auf php8 erhalte ich folgende Fehler, die es zu beheben gilt:
```
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Warning: Undefined array key "pfix" in /volume3/web/php8test/includes/db.class.php on line 298 
Fatal error: Uncaught Error: Call to undefined function mysql_query() in /volume3/web/php8test/includes/db.class.php:133 
Stack trace: 
#0 /volume3/web/php8test/includes/functions.inc.php(107): DatabaseConnection->select('SELECT * FROM `...') 
#1 /volume3/web/php8test/includes/ini.inc.php(91): readPrefs(Object(DatabaseConnection)) 
#2 /volume3/web/php8test/index.php(13): require_once('/volume3/web/ph...') 
#3 {main} thrown in /volume3/web/php8test/includes/db.class.php on line 133
```

**Comment by petertroeger** [comment]
Mit dem aktuellen Code funktioniert es bei mir wieder bei PHP 8.1

**Comment by geimist** [comment]
Ich wusste gar nicht mir, dass es hier noch ein offenes Issue gab. 😬

Closed with https://github.com/geimist/GuestCal/releases/tag/2.1.7
